export const config_variables ={
    BASE_URL: 'http://localhost:3000',
    API_URL: '/api',
    INFO_URL: '/info',  
    LOGIN_URL: '/',
    REGISTER_URL: '/register',
    CHAT_URL: '/chat',
    USER_URL: '/api/user',
    USER_CREATE: '/api/user',
    USER_LIST: '/api/user',
    USER_READ: '/api/user',
    USER_UPDATE: '/api/user',
    USER_DELETE: '/api/user',
    USER_GENERATE_OTP: '/api/user/generate-otp',
    USER_VERIFY_OTP: '/api/user/verify-otp',
    USER_LOGIN: '/api/user/login',
    USER_REGISTER: '/api/user',
    CREATE_CHAT_URI: '/api/chat',
}
