// export const config_variables ={
//     BASE_URL: 'http://localhost:3000',
//     API_URL: 'http://localhost:3000/api',
//     INFO_URL: 'http://localhost:3000/info.html',  
//     LOGIN_URL: 'http://localhost:3000/index.html',
//     REGISTER_URL: 'http://localhost:3000/register.html',
//     CHAT_URL: 'http://localhost:3000/chat.html',
//     USER_URL: 'http://localhost:3000/api/user',
//     USER_CREATE: 'http://localhost:3000/api/user',
//     USER_LIST: 'http://localhost:3000/api/user',
//     USER_READ: 'http://localhost:3000/api/user',
//     USER_UPDATE: 'http://localhost:3000/api/user',
//     USER_DELETE: 'http://localhost:3000/api/user',
//     USER_GENERATE_OTP: 'http://localhost:3000/api/user/generate-otp',
//     USER_VERIFY_OTP: 'http://localhost:3000/api/user/verify-otp',
//     USER_LOGIN: 'http://localhost:3000/api/user/login',
//     USER_REGISTER: 'http://localhost:3000/api/user',
//     CREATE_CHAT_URI: 'http://localhost:3000/api/chat',
// }
export const config_variables ={
    BASE_URL: '',
    API_URL: '/api',
    INFO_URL: '/info.html',  
    LOGIN_URL: '/index.html',
    REGISTER_URL: '/register.html',
    CHAT_URL: '/chat.html',
    USER_URL: '/api/user',
    USER_CREATE: '/api/user',
    USER_LIST: '/api/user',
    USER_READ: '/api/user',
    USER_UPDATE: '/api/user',
    USER_DELETE: '/api/user',
    USER_GENERATE_OTP: '/api/user/generate-otp',
    USER_VERIFY_OTP: '/api/user/verify-otp',
    USER_LOGIN: '/api/user/login',
    USER_REGISTER: '/api/user',
    CREATE_CHAT_URI: '/api/chat',
}