export const config_variables ={
    BASE_URL: 'http://localhost:3000',
    API_URL: 'http://localhost:3000/api',
    INFO_URL: 'http://localhost:3000/info.html',  
    LOGIN_URL: 'http://localhost:3000/index.html',
    REGISTER_URL: 'http://localhost:3000/register.html',
    CHAT_URL: 'http://localhost:3000/chat.html',
    USER_URL: 'http://localhost:3000/api/user',
    USER_CREATE: 'http://localhost:3000/api/user',
    USER_LIST: 'http://localhost:3000/api/user',
    USER_READ: 'http://localhost:3000/api/user',
    USER_UPDATE: 'http://localhost:3000/api/user',
    USER_DELETE: 'http://localhost:3000/api/user',
    USER_GENERATE_OTP: 'http://localhost:3000/api/user/generate-otp',
    USER_VERIFY_OTP: 'http://localhost:3000/api/user/verify-otp',
    USER_LOGIN: 'http://localhost:3000/api/user/login',
    USER_REGISTER: 'http://localhost:3000/api/user',
    CREATE_CHAT_URI: 'http://localhost:3000/api/chat',
}